### ISSUE TITLE
Suggest : Furl timeout setting

### ISSUE THREAD

**Issue by adokoy001** [masakyst/Net-OpenStack-Swift#9]
Hello, masakyst san.
Thank you for your useful CPAN module.

I suggest adding Furl timeout setting parameter at creating Net::OpenStack::Swift Object as below.

```

my $sw = Net::OpenStack::Swift->new(
    auth_url => '',
    user => '',
    password => '',
    auth_version => '',
    tenant_name => '',
    timeout => 20
);

```

**Comment by masakyst** [comment]
thank you!! ship it!
